### ISSUE TITLE
java.util.InputMismatchException during course parse for Summer 2015

### ISSUE THREAD

**Issue by mikereinhold** [CourseScheduler/scheduler-legacy#29]
When downloading and parsing course data for Summer 2015, the download will hang or complete without retrieving all data.

Console log contains:

'''
java.util.InputMismatchException: null
	at java.util.Scanner.throwFor(Scanner.java:864) ~[na:1.8.0_25]
	at java.util.Scanner.next(Scanner.java:1485) ~[na:1.8.0_25]
	at java.util.Scanner.nextDouble(Scanner.java:2413) ~[na:1.8.0_25]
	at io.devyse.scheduler.parse.jsoup.banner.CourseParser.parseCatalogEntry(CourseParser.java:168) ~[scheduler-legacy-4.12.7.jar:4.12.7]
	at io.devyse.scheduler.parse.jsoup.banner.CourseParser.parse(CourseParser.java:115) ~[scheduler-legacy-4.12.7.jar:4.12.7]
	at io.devyse.scheduler.parse.jsoup.AbstractParser.exec(AbstractParser.java:111) ~[scheduler-legacy-4.12.7.jar:4.12.7]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_25]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) [na:1.8.0_25]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) [na:1.8.0_25]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) [na:1.8.0_25]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)[na:1.8.0_25]
'''

**Comment by mikereinhold** [comment]
Fixed in release 4.12.8
