### ISSUE TITLE
Download Course Data fail intermittently w/  SocketTimeoutException

### ISSUE THREAD

**Issue by mikereinhold** [CourseScheduler/scheduler-legacy#32]
When downloading course data, the progress bar blocks at "Querying Course Data from Banner".

Console log shows output similar to the following:

14:35:03.006 [pool-1-thread-1] INFO  Scheduler.Parser - Checking available terms in Banner
14:35:06.840 [pool-1-thread-1] INFO  Scheduler.Parser - Querying course data from Banner
14:35:09.852 [ForkJoinPool-1-worker-1] ERROR i.d.s.parse.jsoup.AbstractParser - Unable to parse the source document: <document content snipped>
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_45]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_45]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_45]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_45]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_45]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_45]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961) ~[na:1.8.0_45]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:918) ~[na:1.8.0_45]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_45]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_45]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_45]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_45]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_45]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[na:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_45]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_45]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:453) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181) ~[jsoup-1.8.1.jar:na]
	at io.devyse.scheduler.parse.jsoup.FormParser.submitForm(FormParser.java:173) ~[classes/:na]
	at io.devyse.scheduler.parse.jsoup.FormParser.parse(FormParser.java:106) ~[classes/:na]
	at io.devyse.scheduler.parse.jsoup.AbstractParser.exec(AbstractParser.java:111) ~[classes/:na]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_45]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [na:1.8.0_45]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [na:1.8.0_45]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_45]

**Comment by mikereinhold** [comment]
The response times of the server have increased to the point where retrieving data may fail intermittently. 

Fix: Add configurable timeouts to the relevant connections

The data retrieval also needs to be more transparent regarding failed downloads.

**Comment by mikereinhold** [comment]
Fixed in release 4.12.9
