### ISSUE TITLE
Server selected improper cipher suite SSL_RSA_WITH_RC4_128_MD5

### ISSUE THREAD

**Issue by fjawor** [CourseScheduler/scheduler-legacy#34]
Cannot download course set from banner
Log:
13:23:40.323 [main] INFO  io.devyse.scheduler.logging.Logging - JUL to SLF4J bridge initialized
13:23:40.362 [main] ERROR i.d.s.s.SingleInstanceController - Unable to register as a single instance listener
javax.jnlp.UnavailableServiceException: uninitialized
	at javax.jnlp.ServiceManager.lookup(Unknown Source) ~[javaws.jar:na]
	at io.devyse.scheduler.startup.SingleInstanceController.register(SingleInstanceController.java:79) ~[classes/:na]
	at Scheduler.Main.main(Main.java:122) [classes/:na]
13:23:40.816 [main] ERROR Scheduler.Serial - Unable to deserialize object
java.io.FileNotFoundException: C:\Users\Frank\Scheduler\Data\201504.sdb (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_51]
	at java.io.FileInputStream.open(Unknown Source) ~[na:1.8.0_51]
	at java.io.FileInputStream.<init>(Unknown Source) ~[na:1.8.0_51]
	at Scheduler.Serial.load(Serial.java:84) ~[classes/:na]
	at Scheduler.Database.load(Database.java:500) [classes/:na]
	at Scheduler.Main.main(Main.java:169) [classes/:na]
13:23:40.954 [main] ERROR i.d.s.analytics.keen.KeenEngine - Unable to load keen configuration file (config/keen.properties): 
java.io.FileNotFoundException: config\keen.properties (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_51]
	at java.io.FileInputStream.open(Unknown Source) ~[na:1.8.0_51]
	at java.io.FileInputStream.<init>(Unknown Source) ~[na:1.8.0_51]
	at java.io.FileInputStream.<init>(Unknown Source) ~[na:1.8.0_51]
	at io.devyse.scheduler.analytics.keen.KeenEngine.configureKeenClient(KeenEngine.java:308) [classes/:na]
	at io.devyse.scheduler.analytics.keen.KeenEngine.initialize(KeenEngine.java:280) [classes/:na]
	at io.devyse.scheduler.analytics.keen.KeenEngine.getDefaultKeenEngine(KeenEngine.java:530) [classes/:na]
	at Scheduler.Main.registerStartupEvent(Main.java:260) [classes/:na]
	at Scheduler.Main.main(Main.java:171) [classes/:na]
13:23:40.954 [main] ERROR i.d.s.analytics.keen.KeenEngine - Unable to initialize Keen IO Analytics
java.io.FileNotFoundException: config\keen.properties (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_51]
	at java.io.FileInputStream.open(Unknown Source) ~[na:1.8.0_51]
	at java.io.FileInputStream.<init>(Unknown Source) ~[na:1.8.0_51]
	at java.io.FileInputStream.<init>(Unknown Source) ~[na:1.8.0_51]
	at io.devyse.scheduler.analytics.keen.KeenEngine.configureKeenClient(KeenEngine.java:308) [classes/:na]
	at io.devyse.scheduler.analytics.keen.KeenEngine.initialize(KeenEngine.java:280) [classes/:na]
	at io.devyse.scheduler.analytics.keen.KeenEngine.getDefaultKeenEngine(KeenEngine.java:530) [classes/:na]
	at Scheduler.Main.registerStartupEvent(Main.java:260) [classes/:na]
	at Scheduler.Main.main(Main.java:171) [classes/:na]
13:23:41.974 [main] INFO  Scheduler.Main - java.version: 1.8.0_51
13:23:41.974 [main] INFO  Scheduler.Main - java.vm.specification.version: 1.8
13:23:41.974 [main] INFO  Scheduler.Main - java.vm.version: 25.51-b03
13:23:41.975 [main] INFO  Scheduler.Main - java.specification.version: 1.8
13:23:41.975 [main] INFO  Scheduler.Main - java.class.version: 52.0
13:23:47.869 [pool-1-thread-1] INFO  Scheduler.Parser - Checking available terms in Banner
13:23:51.264 [pool-1-thread-1] ERROR Scheduler.Parser - Error retrieving or parsing course dataset from Banner
javax.net.ssl.SSLException: Server selected improper ciphersuite SSL_RSA_WITH_RC4_128_MD5
	at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverHello(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:1.8.0_51]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181) ~[jsoup-1.8.1.jar:na]
	at Scheduler.Parser.jsoupParse(Parser.java:167) [classes/:na]
	at Scheduler.Parser.parseKUCourses(Parser.java:144) [classes/:na]
	at Scheduler.Parser.parseCourses(Parser.java:276) [classes/:na]
	at Scheduler.ParseThread.doInBackground(ParseThread.java:94) [classes/:na]
	at Scheduler.ParseThread.doInBackground(ParseThread.java:1) [classes/:na]
	at javax.swing.SwingWorker$1.call(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_51]
	at javax.swing.SwingWorker.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_51]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_51]
13:24:16.276 [pool-1-thread-29] INFO  Scheduler.Parser - Checking available terms in Banner
13:24:16.304 [pool-1-thread-29] ERROR Scheduler.Parser - Error retrieving or parsing course dataset from Banner
javax.net.ssl.SSLException: Server selected improper ciphersuite SSL_RSA_WITH_RC4_128_MD5
	at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverHello(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:1.8.0_51]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181) ~[jsoup-1.8.1.jar:na]
	at Scheduler.Parser.jsoupParse(Parser.java:167) [classes/:na]
	at Scheduler.Parser.parseKUCourses(Parser.java:144) [classes/:na]
	at Scheduler.Parser.parseCourses(Parser.java:276) [classes/:na]
	at Scheduler.ParseThread.doInBackground(ParseThread.java:94) [classes/:na]
	at Scheduler.ParseThread.doInBackground(ParseThread.java:1) [classes/:na]
	at javax.swing.SwingWorker$1.call(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_51]
	at javax.swing.SwingWorker.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_51]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_51]
13:26:13.490 [pool-1-thread-57] INFO  Scheduler.Parser - Checking available terms in Banner
13:26:13.517 [pool-1-thread-57] ERROR Scheduler.Parser - Error retrieving or parsing course dataset from Banner
javax.net.ssl.SSLException: Server selected improper ciphersuite SSL_RSA_WITH_RC4_128_MD5
	at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverHello(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:1.8.0_51]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434) ~[jsoup-1.8.1.jar:na]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181) ~[jsoup-1.8.1.jar:na]
	at Scheduler.Parser.jsoupParse(Parser.java:167) [classes/:na]
	at Scheduler.Parser.parseKUCourses(Parser.java:144) [classes/:na]
	at Scheduler.Parser.parseCourses(Parser.java:276) [classes/:na]
	at Scheduler.ParseThread.doInBackground(ParseThread.java:94) [classes/:na]
	at Scheduler.ParseThread.doInBackground(ParseThread.java:1) [classes/:na]
	at javax.swing.SwingWorker$1.call(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_51]
	at javax.swing.SwingWorker.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_51]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_51]

**Comment by mikereinhold** [comment]
@Fjawor thanks for reporting. Sorry for the inconvenience

That's an odd error because according to http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html, SSL_RSA_WITH_RC4_128_MD5 should be enabled by default for any modern JRE.

From the log, it looks like you're running Java 1.8u51 on Windows- can you confirm the Java version, Windows version, and if 64 bit Windows is it also a 64bit JRE? Oracle JRE or third party? How are you launching the application? I see an exception in registering the Single Instance Server during startup- probably unrelated but still interesting as that should only occur if launched standalone and not via WebStart.

Let me know the answers to the above - I'll try and reproduce the issue

**Comment by fjawor** [comment]
Hi,
I am running Java 1.8u51 on 65bit Windows also 64bit JRE from Oracle. I am
simply downloading the automatic latest version from SourceForge. Whenever
I try to create a new schedule, it says the operation failed because I need
to download the course schedule. Then I click download course set and it
shows downloading data from ratemyprofessors but not banner.
Thank you

**Comment by mikereinhold** [comment]
@fjawor Looks like Oracle has [disabled RC4](http://www.oracle.com/technetwork/java/javase/8all-relnotes-2226344.html) in 1.8u51 as being considered insecure (even though original 1.8 release info included this particular cipher combination). 

>Area: security-libs/javax.net.ssl
Synopsis: Deprecate RC4 in SunJSSE provider

>RC4 is now considered as a weak cipher. Servers should not select RC4 unless there is no other stronger candidate in the client requested cipher suites. A new security property, jdk.tls.legacyAlgorithms, is added to define the legacy algorithms in Oracle JSSE implementation. RC4 related algorithms are added to the legacy algorithms list.

>See JDK-8074006 (not public).

>Area: security-libs/javax.net.ssl
Synopsis: Prohibit RC4 cipher suites

>RC4 is now considered as a compromised cipher. RC4 cipher suites have been removed from both client and server default enabled cipher suite list in Oracle JSSE implementation. These cipher suites can still be enabled by SSLEngine.setEnabledCipherSuites() and SSLSocket.setEnabledCipherSuites() methods.

>See JDK-8077109 (not public).

As a result, the client is rejecting the secure connection due to RC4 being selected by the server. 

There are a couple of different ways to resolve this issue:
* Convince Kettering to change their server config to prefer stronger ciphers. Also, to change their SSL certificate even though it doesn't expire for a year:  their cert has SHA1 hashes and selects other weak ciphers besides RC4 such as 3DES (verified in Chrome and Firefox)
* I may be able to programmatically request/prefer/force a stronger cipher
* override the disable of RC4 (undesirable for obvious reasons). 

It's going to take me a bit to determine the best way to handle this - I absolutely do not want to enable a deprecated cipher unless it is 100% unavoidable...

In the meantime, I've verified that this works as expected in previous JRE versions, such as 8u45. I recommend you install 8u45 and temporarily disable 8u51 until I can release a version that works around this.

**Comment by fjawor** [comment]
Ok. Cool. Thanks.

**Comment by fjawor** [comment]
I downgraded my java version to 8u45 and now when querying course data from banner, the application just hangs.

**Comment by mikereinhold** [comment]
Results of testing accepted ciphers against jweb.kettering.edu:

> Obtaining cipher list from OpenSSL 1.0.2d 9 Jul 2015.
Testing ciphers against jweb.kettering.edu:443
Testing ECDHE-RSA-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing ECDHE-RSA-AES256-SHA384...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-AES256-SHA384...NO (sslv3 alert handshake failure)
Testing ECDHE-RSA-AES256-SHA...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-AES256-SHA...NO (sslv3 alert handshake failure)
Testing SRP-DSS-AES-256-CBC-SHA...NO (no ciphers available)
Testing SRP-RSA-AES-256-CBC-SHA...NO (no ciphers available)
Testing SRP-AES-256-CBC-SHA...NO (no ciphers available)
Testing DH-DSS-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing DHE-DSS-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing DH-RSA-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing DHE-RSA-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing DHE-RSA-AES256-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-DSS-AES256-SHA256...NO (sslv3 alert handshake failure)
Testing DH-RSA-AES256-SHA256...NO (sslv3 alert handshake failure)
Testing DH-DSS-AES256-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-RSA-AES256-SHA...NO (sslv3 alert handshake failure)
Testing DHE-DSS-AES256-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-AES256-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-AES256-SHA...NO (sslv3 alert handshake failure)
Testing DHE-RSA-CAMELLIA256-SHA...NO (sslv3 alert handshake failure)
Testing DHE-DSS-CAMELLIA256-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-CAMELLIA256-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-CAMELLIA256-SHA...NO (sslv3 alert handshake failure)
Testing AECDH-AES256-SHA...NO (sslv3 alert handshake failure)
Testing ADH-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing ADH-AES256-SHA256...NO (sslv3 alert handshake failure)
Testing ADH-AES256-SHA...NO (sslv3 alert handshake failure)
Testing ADH-CAMELLIA256-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-AES256-SHA384...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-AES256-SHA384...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-AES256-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-AES256-SHA...NO (sslv3 alert handshake failure)
Testing AES256-GCM-SHA384...NO (sslv3 alert handshake failure)
Testing AES256-SHA256...NO (sslv3 alert handshake failure)
Testing AES256-SHA...NO (sslv3 alert handshake failure)
Testing CAMELLIA256-SHA...NO (sslv3 alert handshake failure)
Testing PSK-AES256-CBC-SHA...NO (no ciphers available)
Testing ECDHE-RSA-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing ECDHE-RSA-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing ECDHE-RSA-AES128-SHA...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-AES128-SHA...NO (sslv3 alert handshake failure)
Testing SRP-DSS-AES-128-CBC-SHA...NO (no ciphers available)
Testing SRP-RSA-AES-128-CBC-SHA...NO (no ciphers available)
Testing SRP-AES-128-CBC-SHA...NO (no ciphers available)
Testing SRP-AES-128-CBC-SHA...NO (no ciphers available)
Testing DH-DSS-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-DSS-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing DH-RSA-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-RSA-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-RSA-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-DSS-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing DH-RSA-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing DH-DSS-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing DHE-RSA-AES128-SHA...NO (sslv3 alert handshake failure)
Testing DHE-DSS-AES128-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-AES128-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-AES128-SHA...NO (sslv3 alert handshake failure)
Testing DHE-RSA-SEED-SHA...NO (sslv3 alert handshake failure)
Testing DHE-DSS-SEED-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-SEED-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-SEED-SHA...NO (sslv3 alert handshake failure)
Testing DHE-RSA-CAMELLIA128-SHA...NO (sslv3 alert handshake failure)
Testing DHE-DSS-CAMELLIA128-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-CAMELLIA128-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-CAMELLIA128-SHA...NO (sslv3 alert handshake failure)
Testing AECDH-AES128-SHA...NO (sslv3 alert handshake failure)
Testing ADH-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing ADH-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing ADH-AES128-SHA...NO (sslv3 alert handshake failure)
Testing ADH-SEED-SHA...NO (sslv3 alert handshake failure)
Testing ADH-CAMELLIA128-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-AES128-SHA256...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-AES128-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-AES128-SHA...NO (sslv3 alert handshake failure)
Testing AES128-GCM-SHA256...NO (sslv3 alert handshake failure)
Testing AES128-SHA256...NO (sslv3 alert handshake failure)
Testing AES128-SHA...NO (sslv3 alert handshake failure)
Testing SEED-SHA...NO (sslv3 alert handshake failure)
Testing CAMELLIA128-SHA...NO (sslv3 alert handshake failure)
Testing IDEA-CBC-SHA...NO (sslv3 alert handshake failure)
Testing IDEA-CBC-MD5...NO (sslv3 alert handshake failure)
Testing RC2-CBC-MD5...NO (sslv3 alert handshake failure)
Testing PSK-AES128-CBC-SHA...NO (no ciphers available)
Testing ECDHE-RSA-RC4-SHA...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-RC4-SHA...NO (sslv3 alert handshake failure)
Testing AECDH-RC4-SHA...NO (sslv3 alert handshake failure)
Testing ADH-RC4-MD5...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-RC4-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-RC4-SHA...NO (sslv3 alert handshake failure)
Testing RC4-SHA...YES
Testing RC4-MD5...YES
Testing RC4-MD5...YES
Testing PSK-RC4-SHA...NO (no ciphers available)
Testing ECDHE-RSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing SRP-DSS-3DES-EDE-CBC-SHA...NO (no ciphers available)
Testing SRP-RSA-3DES-EDE-CBC-SHA...NO (no ciphers available)
Testing SRP-3DES-EDE-CBC-SHA...NO (no ciphers available)
Testing EDH-RSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing EDH-DSS-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing AECDH-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ADH-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-DES-CBC3-SHA...NO (sslv3 alert handshake failure)
Testing DES-CBC3-SHA...YES
Testing DES-CBC3-MD5...NO (sslv3 alert handshake failure)
Testing PSK-3DES-EDE-CBC-SHA...NO (no ciphers available)
Testing EDH-RSA-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing EDH-DSS-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing DH-RSA-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing DH-DSS-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing ADH-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing DES-CBC-SHA...YES
Testing DES-CBC-MD5...NO (sslv3 alert handshake failure)
Testing EXP-EDH-RSA-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing EXP-EDH-DSS-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing EXP-ADH-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing EXP-DES-CBC-SHA...NO (sslv3 alert handshake failure)
Testing EXP-RC2-CBC-MD5...NO (sslv3 alert handshake failure)
Testing EXP-RC2-CBC-MD5...NO (sslv3 alert handshake failure)
Testing EXP-ADH-RC4-MD5...NO (sslv3 alert handshake failure)
Testing EXP-RC4-MD5...NO (sslv3 alert handshake failure)
Testing EXP-RC4-MD5...NO (sslv3 alert handshake failure)
Testing ECDHE-RSA-NULL-SHA...NO (sslv3 alert handshake failure)
Testing ECDHE-ECDSA-NULL-SHA...NO (sslv3 alert handshake failure)
Testing AECDH-NULL-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-RSA-NULL-SHA...NO (sslv3 alert handshake failure)
Testing ECDH-ECDSA-NULL-SHA...NO (sslv3 alert handshake failure)
Testing NULL-SHA256...NO (sslv3 alert handshake failure)
Testing NULL-SHA...NO (sslv3 alert handshake failure)
Testing NULL-MD5...NO (sslv3 alert handshake failure)

**Comment by mikereinhold** [comment]
@fjawor check out the latest version, 4.12.9. Download and run the JNLP for 4.12.9 from the releases section - this should update you to the latest version which resolved the hang you described (tracked as issue #32).

**Comment by mikereinhold** [comment]
Releasing 4.12.10
