### ISSUE TITLE
NPE when retrieving for Winter 2016

### ISSUE THREAD

**Issue by mikereinhold** [CourseScheduler/scheduler-legacy#38]
NullPointerException when retrieving course data for Winter 2016

>java.lang.NullPointerException: null
    at io.devyse.scheduler.parse.jsoup.banner.TermSelectionParser.buildFormParameters(TermSelectionParser.java:117) ~[scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at io.devyse.scheduler.parse.jsoup.FormParser.parse(FormParser.java:105) ~[scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at io.devyse.scheduler.parse.jsoup.AbstractParser.exec(AbstractParser.java:135) ~[scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_45]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [na:1.8.0_45]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [na:1.8.0_45]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_45]
23:03:26.727 [pool-1-thread-1] ERROR Scheduler.Parser - Error retrieving or parsing course dataset from Banner
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2613) ~[na:1.8.0_45]
    at Scheduler.Parser.jsoupParse(Parser.java:175) [scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at Scheduler.Parser.parseKUCourses(Parser.java:144) [scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at Scheduler.Parser.parseCourses(Parser.java:276) [scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at Scheduler.ParseThread.doInBackground(ParseThread.java:94) [scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]
    at Scheduler.ParseThread.doInBackground(ParseThread.java:53) [scheduler-legacy-4.12.9-SNAPSHOT.jar:4.12.9-SNAPSHOT]

**Comment by mikereinhold** [comment]
NullPointerException is presented because Winter 2016 is not yet available on BannerWeb for download. 

This error should be caught and presented to the user more transparently so that the real root cause is clear. Bigger picture, term selection should be altered to only allow selection of terms which are available on BannerWeb.

**Comment by mikereinhold** [comment]
Releasing 4.12.10
